id = "adaptify"
name = "Adaptify"
version = "0.2.3"
schema_version = 1
authors = ["Jovanni Lo <lodev09@gmail.com>"]
description = "A beautiful, adaptive theme for your Zed editor"
repository = "https://github.com/lodev09/adaptify-zed"
