id = "adaptify"
name = "Adaptify"
version = "0.1.0"
schema_version = 1
authors = ["Jovanni Lo"]
description = "A beautiful, adaptive dark theme for your Zed editor"
repository = "https://github.com/lodev09/adaptify-zed"
